#!/bin/bash 

set -x            # debug-mode

set -e            # exits script when there is error

set -o            # pipefail

df -h

free

top

nproc

ps -ef | grep "amazon" | awk -F" " '{print $1,$2,$3}'
